<?php

/**
 * @file
 * Contains commerce_cattributes.module.
 */

use Drupal\commerce_cattributes\Plugin\Field\FieldWidget\CorrectProductVariationAttributesWidget;
use Drupal\commerce_cattributes\Plugin\Field\FieldWidget\CorrectProductVariationTitleWidget;

/**
 * Implements hook_field_widget_info_alter().
 */
function commerce_cattributes_field_widget_info_alter(array &$info) {
  $info['commerce_product_variation_title']['class'] = CorrectProductVariationTitleWidget::class;
  $info['commerce_product_variation_attributes']['class'] = CorrectProductVariationAttributesWidget::class;
}

/**
 * Implements hook_element_info_alter().
 */
function commerce_cattributes_element_info_alter(array &$info) {
  if (isset($info['commerce_product_rendered_attribute'])) {

    /**
     * Alters element processing class.
     */
    function commerce_cattributes_alter_element(&$item) {
      if (is_array($item)) {
        array_walk($item, 'commerce_cattributes_alter_element');
      }
      elseif ($item === 'Drupal\commerce_product\Element\CommerceProductRenderedAttribute') {
        $item = 'Drupal\commerce_cattributes\Element\CorrectCommerceProductRenderedAttribute';
      }
    }

    array_walk($info['commerce_product_rendered_attribute'], 'commerce_cattributes_alter_element');
  }
}
